# Generated by Django 2.1.5 on 2019-01-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_material_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
