# Generated by Django 2.1.5 on 2019-01-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190120_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['status', 'created']},
        ),
    ]
