# Generated by Django 2.1.5 on 2019-01-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190120_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Material')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companyprice',
            unique_together={('company', 'material')},
        ),
    ]
