# Generated by Django 2.1.5 on 2019-01-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190120_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='jobs.Company'),
        ),
    ]
